### ISSUE TITLE
Add discount component to PPPI Module

### ISSUE THREAD

**Issue by ranafaraz** [ranafaraz/TCBApp_RAW_Code#10]
## Directions
Add discount in **Products per Purchase Invoice** module. Discount can be added on the sum of all the items in an purchase invoice and can also be added as "discount per item".

**Comment by Aqsa099** [comment]
- pppi module required discount module for individual product and whole invoice

- This issue is solved ,we set discount  by percentage and by amount and at the end sum of "discount array" is the total_discount of one invoice.
