### ISSUE TITLE
Individual_Discount_for_products 

### ISSUE THREAD

**Issue by Aqsa099** [ranafaraz/TCBApp_RAW_Code#11]
- in products_per_purchase_invoice form required a discount field for each product separately. 

- we should display discount both by "percentage" and by "amount"

-

**Comment by ranafaraz** [comment]
# Logical Error on Add Product Form
1. The textbox **Purchase Price** is not populated without clicking the radio buttons while a radio button is selected by default and its a logical error.
2. Kindly use the on change function to perform this task and made the function to apply discount without clicking any radio button and to populate the textbox **Purchase Price** as well.

**Comment by ranafaraz** [comment]
# Screen shot of the problem:
![discount_not_working](https://user-images.githubusercontent.com/26284885/34462434-d245c382-ee65-11e7-87b4-aa5990b04692.png)

**Comment by ranafaraz** [comment]
# Create a separate OnChange function to apply discount:
### Here is the sample code from another application (Fatima Clinical Labs). Change the attributes according to your need.

<script>
function myFunction() {
        var x = document.getElementById("total").value;
	var y = document.getElementById("discount").value;
	var sub = x - y;
	document.getElementById("demo").value =  sub;
}
</script>

<form method="POST">
        	<table width="100%">
			<tr>
	                	<th align="left">Total Price</th>
                    		<td align="center"><input type="text" id="total" name="totalprice" value="<?php echo $total_sum["0"]; ?>"  size="5" readonly /> </td>   
                	</tr>
    	        	<tr>
	                	<th align="left">Discount</th>
                    		<td align="center"><input type="text" id="discount" name="discount" value="0" onchange="myFunction()" size="5" /> </td>   
                	</tr>
                	<tr>
        	        	<th align="left">Paid</th>
                    		<td align="center"><input type="text" value="<?php echo $total_sum["0"]; ?>" name="paid" id="demo" size="5" /></td>
                	</tr>
			<tr>
				<th colspan="2">
				<input type="submit" class="noprint" style="padding: 5px 20px" value="Paid" name="submit" onclick="window.print()"/>
				</th>
			</tr>
	        </table>
	</div>
</form>

**Comment by Aqsa099** [comment]
- Issue have been solved about discount per products and discount per invoice
