### ISSUE TITLE
Files in the Github repo are not working

### ISSUE THREAD

**Issue by ranafaraz** [ranafaraz/TCBApp_RAW_Code#16]
Issue:
The files in the github repository are not working on localhost. This might be because of merging pull requests from multiple users after resolving their conflicts in a non-professional way.
Kindly do resolve the issue as soon as possible by cloning the repo on your localhost and tracing the problem.
Screen shot is attached.
![purchase_invoice](https://user-images.githubusercontent.com/26284885/34461879-9374ad56-ee58-11e7-8124-7ffef12b06c9.png)

**Comment by Aqsa099** [comment]
- These conflicts are occurs due to missing some lines of code or brackets in some files.

- Now these are resolved
