### ISSUE TITLE
Products are not being added

### ISSUE THREAD

**Issue by ranafaraz** [ranafaraz/TCBApp_RAW_Code#18]
![error_adding_products](https://user-images.githubusercontent.com/26284885/34462545-045e2a88-ee68-11e7-983f-094cdf0d4492.png)

**Comment by ranafaraz** [comment]
# An error occurred while adding new products in an invoice. See screen shot for further details.

**Comment by Aqsa099** [comment]
- Products insert successfully against invoice id
